double ** BasePairProbabilities(char * , int, double * , char* , double *, int);
double energyOfStructure(char * , char *);
double structureProbability(double, double);
double expectedPositionalEntropy(double ** , int,int);
double morganHiggsStructuralDiversity (double ** , int);
double viennaStructuralDiversity (double ** , int);
double expectedBpDistance(double ** , int , char *);
double ensembleDefect(double ** , int , char *);
double expectedNumborOfBasepairs(double ** , int);
double expectedPropOfTargetContacts(double ** , int , char *);
double ensembleHammingDistance(double **, double **, int);
double ensembleBasePairDistance(double ** , double **, int );
double positionalEntropyDistance(double ** , double ** , int);
double epsilonNearExpectedBpDistance(double ** , int  , char * , int );
double epsilonNearEnsembleDefect(double **, int  , char * ,int );
void printPositionalEntropy(double ** , int , int );
int * getBasePairs(char * , int);
double RodrigoRobustness(double ** , int , char *);
double ensembleVariationDistance(double ** , double ** , int);
double expected2DcontactOrder(double ** , int , char * );	
void expectedHeight(double **, int );
void expectedModifiedHeight(double **, int );
void printTriProbabilities(double **bppr , int n);
